export const HELP = {
  workoutBuilder: {
    template: "Aplica una estructura inicial con bloques y movimientos sugeridos. Después puedes editar cada campo.",
    title: "Nombre corto del test/workout. Ejemplo: 'Fran Variación'.",
    description: "Explica objetivo, estímulo y criterios de ejecución en 1-3 líneas.",
    workoutType: "Define el formato general (AMRAP, EMOM, For Time, etc.). Condiciona cómo se interpreta el resultado.",
    scoreType: "Tipo de resultado principal que se guardará. Ejemplo: tiempo total o repeticiones.",
    visibility: "COMMUNITY publica para toda la comunidad; PRIVATE lo deja solo para tu entorno.",
    duration: "Duración de referencia para vista rápida. En este builder se calcula por estructura.",
    blockType: "WORK suma carga de trabajo; REST crea pausas entre segmentos.",
    repeatInt: "Cantidad de repeticiones del bloque dentro del diseño.",
    timeSeconds: "Tiempo objetivo del bloque en segundos. Ejemplo: 300 = 5 minutos.",
    capSeconds: "Límite máximo permitido para cerrar el bloque o test.",
    reps: "Repeticiones objetivo para ese movimiento.",
    meters: "Distancia objetivo en metros para carrera, remo o trineo.",
    seconds: "Tiempo objetivo del movimiento específico en segundos.",
    calories: "Calorías objetivo cuando el implemento reporta este dato (bike/row/ski).",
    loadRule: "Regla de carga: FIXED usa valor fijo, PERCENTAGE ajusta por referencia del atleta.",
    boxHeightCm: "Altura del cajón en centímetros para variantes de box jump/step-up.",
    notes: "Indicaciones técnicas o estándares de movimiento para jueceo consistente.",
  },
  coachMetrics: {
    athletes: "Total de atletas activos asignados al coach en el gimnasio seleccionado.",
    pendingValidations: "Intentos enviados por atletas que aún requieren revisión.",
    validatedToday: "Intentos validados hoy por el coach. Sirve para medir flujo operativo diario.",
    level: "Nivel actual estimado del atleta según su historial validado.",
    levelBand: "Rango cualitativo del nivel (ej. Bronze, Silver) para lectura rápida.",
  },
  athleteMetrics: {
    pulseScore: "Índice compuesto (0-100) del estado global del atleta según capacidades y consistencia reciente.",
    pulseConfidence: "Indica cuánta evidencia real respalda el score (LOW/MEDIUM/HIGH).",
    strength: "Capacidad para mover altas cargas con técnica correcta.",
    muscularEndurance: "Capacidad de sostener repeticiones o esfuerzo muscular prolongado.",
    relativeStrength: "Fuerza en relación al peso corporal del atleta.",
    workCapacity: "Capacidad de mantener volumen e intensidad total en sesiones exigentes.",
    tests7d: "Cantidad de tests registrados en los últimos 7 días.",
    tests30d: "Cantidad de tests registrados en los últimos 30 días.",
    trends30d: "Variación reciente por capacidad: positivo sugiere mejora, negativo sugiere caída.",
  },
} as const;
